"""empty message

Revision ID: 0b3334e3c42c
Revises: 6f2b4e10c950
Create Date: 2022-11-20 18:22:25.347109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3334e3c42c'
down_revision = '6f2b4e10c950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'created')
    # ### end Alembic commands ###
